version: "3.9"
services:
 system-service:
  image: jsels/eindproject-api-development
  ports:
    - "8001:8001"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
